### ISSUE TITLE
"Show tracker without clicking" example causes application to freeze on linux

### ISSUE THREAD

**Issue by hol430** [oxyplot/oxyplot-gtksharp#13]
### Steps to reproduce

1. Run the gtk3 version of the example browser
2. Click on the "Show tracker without clicking" graph (it's in the PlotController examples section)
3. Move mouse over the lines (not the empty graph area)
4. Application is now unresponsive

Platform:
.NET version: Observed on netcoreapp3.1 and netcoreapp2.1

Based on the discussion in #12, this seems to occur on Linux but not on windows.

### Expected behaviour

I believe the tracker should follow the mouse and show the x/y coordinates. The application should remain responsive.

### Actual behaviour

Application becomes unresponsive. Some brief debugging shows that there's a continuous stream of enter-notify-event and leave-notify-events firing on the plot (GtkLayout) widget, even when the mouse is not moving. Interestingly, if I remove the call to gtk_layout_move() (this.Move() in the ShowTracker() function in PlotView.cs), then the problem disappears. 

![image](https://user-images.githubusercontent.com/36427516/123877159-094cc700-d980-11eb-8c5c-6651cc9c300d.png)

**Comment by d-buchmann** [comment]
I can confirm this behavior.
After some fiddling with `ShowTracker` and the enter/leave events, I found that this chain is called recurringly when the mouse cursor is actually inside the `trackerLabel.Parent` box, even if the mouse doesn't move. As long as the cursor stays outside of the box, it continues to work.
This also happens on Windows, but the application doesn't freeze as the calls stop when moving the mouse away.

I put up a dirty fix like this:
Store the `EventCrossing` in the `OnEnterNotifyEvent` in the `PlotView` class and ignore the `OnLeaveNotifyEvent` if its `X` and `Y` coordinates match. As far as I can tell, this doesn't break anything, but I'll leave it to you @hol430 as to open a PR or not.

Note that the tracker then behaves a little different (I'd say better, as it is also updated when the cursor moves across the box).

**Comment by hol430** [comment]
I think the clue here is in the `Detail` property of the `EventCrossing` argument being passed into the `OnEnterNotifyEvent` and `OnLeaveNotifyEvent`. Under X11 (not sure about the windows backend), this `Detail` property will be set to `NotifyType.Inferior` when the mouse has entered or left the plot (layout) area via an 'inferior' gdk window - such as that behind the tracker label. When we move the label in callback for the the `MotionNotifyEvent`, the label moves slightly which causes the mouse to 'enter' the plot area via the label, so the `Detail` property is set to `NotifyType.Inferior`.

I tested this by ignoring the enter and leave events when the `Detail` property is set to `NotifyType.Inferior`, and this fixes the problem, causing the cycle of redundant enter/leave events to stop. (Well, technically, the layout widget is still receiving those events, but as long as we don't do anything on them, it's not a problem.)

Now it's kind of debatable whether we should be completely ignoring the events in this case - some of the time it could well be safe to pass on the events to the ActualController object (e.g. if the event is coming from a widget added by the user in front of the graph), but in some cases (like this example plot), it results in disaster under X11. So I'm going to push up a tentative fix for this problem using this solution, although I'm certainly open to alternative suggestions; we could for example propagate the events further and keep track of the notify type, and only move the label if the notify type is not `NotifyType.Inferior`.
