### ISSUE TITLE
How To Display Chart in The WIndow?

### ISSUE THREAD

**Issue by seikosantana** [oxyplot/oxyplot-gtksharp#21]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Create an instance of PlotView
2. Add the PlotView to a container
3. See that PlotView isn't subclass of Widget.

Platform:
.NET version: .NET 6

### Expected behaviour

Seeing the documentation in https://oxyplot.readthedocs.io/en/latest/getting-started/hello-gtk.html#result it is .Add()-ed to Window but that isn't possible since we cannot cast PlotView to Widget.

**Comment by hol430** [comment]
For what it's worth, PlotView extends Layout, which extends Container, which extends Widget.

Which version of the library are you using? If you're using the official nuget, I believe this is out of date and still uses the .net framework gtk-sharp (or [gtk-sharp-3](https://github.com/openmedicus/gtk-sharp) if building a gtk3 app - note that this is *not* GtkSharp).

If you're also using [GtkSharp](https://github.com/GtkSharp/GtkSharp), that could be the problem, as PlotView would be subclassing the "wrong" widget type.

**Comment by seikosantana** [comment]
I'm using GtkSharp.
Is there any package that's compatible with it?

**Comment by hol430** [comment]
There's currently no official nuget package which is compatible with GtkSharp, so I've manually built a package which I've uploaded to [myget](https://www.myget.org/feed/hol430/package/nuget/OxyPlot.GtkSharp3/2.0.3-netcorebeta) which I'm using in the interim.

**Comment by seikosantana** [comment]
Thanks.. I will check it out..
