### ISSUE TITLE
Oxyplot Project Site

### ISSUE THREAD

**Issue by seikosantana** [oxyplot/oxyplot-gtksharp#22]
Not really related to technical things, I'm just curious what happened to the project site of oxyplot.

I've seen oxyplot.org leads me to this cat website
![image](https://user-images.githubusercontent.com/35630407/146907454-7f48a448-2551-45e4-9656-9d667d60a6c1.png)

Is the website dead?

**Comment by VisualMelon** [comment]
Yes, `oxyplot.org` is not longer used by the project. See https://github.com/oxyplot/oxyplot/issues/1274 for further details.
